modLoader = "javafml"
loaderVersion = "[40,)"
license = "All rights reserved"
[[mods]]
logoFile = "miners_delight.png"
modId = "miners_delight"
version = "${file.jarVersion}"
displayName = "Miner's Delight"
authors = "Sammy;"
description = '''
A Farmer's Delight addon focused on adding more food variety to caves!
'''
[[dependencies.miners_delight]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.miners_delight]]
modId= "farmersdelight"
mandatory= true
versionRange= "[1.18.2-1.2.0,)"
ordering= "NONE"
side= "BOTH"